name: lighthouse-ci

on: push

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Serve static site
        run: npx http-server out -p 8080 & sleep 2
      - name: Run LHCI autorun
        run: npx -y @lhci/cli@0.8.0 autorun --collect.url=http://localhost:8080 --upload.target=temporary-public-storage
